#!/usr/bin/bash

function die() {
    echo "ERROR: $*"
    exit 99
}

function dumpvars() {
    for vname; do
        echo "$vname => '${!vname}'"
    done
}

PGM=$( basename $0 )
INFODIR=$( dirname $0 )
source $INFODIR/read_ini.sh

PARALLEL=$( which parallel )
[[ -z "$PARALLEL" ]] && die "Unable to find 'parallel'"
[[ -x "$PARALLEL" ]] || die "Parallel program, 'parallel', is not executable"

# Get Original Source
first_dar_ini=$( ls "$INFODIR"/*0001.ini )
[[ -f "$first_dar_ini" ]] || die "Can't find first dar ini file"
read_ini "$first_dar_ini" -p SRC
[[ -z "${SRC__FS_ROOT}" ]] && die "Cound not find FS_ROOT in ini file '$first_dar_ini'"
[[ -d "${SRC__FS_ROOT}" ]] || die "FS_ROOT '${SRC__FS_ROOT}' is not a valid directory"

# Get Restore Root
fn_restore_ini=$( ls "$INFODIR"/restore.ini )
[[ -f "$fn_restore_ini" ]] || dir "Can't find restore.ini file"
read_ini "$fn_restore_ini" -p TGT
[[ -z "${TGT__RESTORE__ROOT}" ]] && die "Could not find RESTORE ROOT in ini file '$fn_restore_ini'"
[[ -d "${TGT__RESTORE__ROOT}" ]] || die "RESTORE ROOT '${TGT__RESTORE__ROOT}' is not a valid directory"

RSYNCLOGBASE="$INFODIR/rsync_compare.out"

dumpvars SRC__FS_ROOT TGT__RESTORE__ROOT INFODIR RSYNCLOGBASE

echo "Continue?"
select yn in Yes No; do
    case $yn in
        Yes ) break;;
          * ) exit;;
    esac
done

### Compare source to restored
# clean up any existing rsync log files
rm ${RSYNCLOGBASE}*

#single-threaded
set -x
rsync -navHAXi ${SRC__FS_ROOT}/ ${TGT__RESTORE__ROOT}/ >"$RSYNCLOGBASE"
set +x
diffcount=$( wc -l "$RSYNCLOGBASE" | cut -d ' ' -f1 )
[[ $diffcount -gt 5 ]] && { echo "Differences found: see file '$RSYNCLOGBASE'"
} || { echo "No differences found!"
}

##parallel
#rsync_opts='-nilptgoHAX'
##### compare top level
####find "${SRC__FS_ROOT}" -mindepth 1 -maxdepth 1 -print0 \
####| parallel -0 -j1 "rsync $rsync_opts ${SRC__FS_ROOT}/{} ${TGT__RESTORE__ROOT}/{} >>${RSYNCLOGBASE}.."
## compare each element in first sub level below top
#rsync_opts='-niaHAX'
#find "${SRC__FS_ROOT}/" -mindepth 1 -maxdepth 1 -type d -name 'aloftus' -printf "%f\0" \
#| parallel -0 -j16 "rsync $rsync_opts ${SRC__FS_ROOT}/{}/ ${TGT__RESTORE__ROOT}/{}/ >${RSYNCLOGBASE}.{}"
